function GRA = find_GRA
%find_GRA
%    GRA = find_GRA

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    17-Jun-2022 20:34:33

GRA = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[15,3]);
