clear all
tic
[INT, GRA, Itheta] = GetTorques_omega;
toc
parallel.defaultClusterProfile('local');
c = parcluster();



job = createJob(c);
createTask(job, @matlabFunction, 1, ...
    { ...
        GRA, ...
        'file', 'find_GRA2.m', ...
        'outputs', {'GRA'}, ...
        'Optimize', false ...
    });
submit(job)
job.Tasks

job = createJob(c);
createTask(job, @matlabFunction, 1, ...
    { ...
        Itheta, ...
        'file', 'find_Itheta2.m', ...
        'outputs', {'Ihteta'}, ...
        'Optimize', false ...
    });
submit(job)
job.Tasks

job = createJob(c);
createTask(job, @matlabFunction, 1, ...
    { ...
        INT, ...
        'file', 'find_INT2.m', ...
        'outputs', {'INT'}, ...
        'Optimize', false ...
    });
submit(job)
job.Tasks

wait(job)


