clear all

[INT, GRA, Itheta] = GetTorques_;

parallel.defaultClusterProfile('local');
c = parcluster();

job = createJob(c);
createTask(job, @matlabFunction, 1, ...
    { ...
        INT, ...
        'file', 'find_INT.m', ...
        'outputs', {'INT'}, ...
        'Optimize', false ...
    });
submit(job)
job.Tasks

job = createJob(c);
createTask(job, @matlabFunction, 1, ...
    { ...
        GRA, ...
        'file', 'find_GRA.m', ...
        'outputs', {'GRA'}, ...
        'Optimize', false ...
    });
submit(job)
job.Tasks

job = createJob(c);
createTask(job, @matlabFunction, 1, ...
    { ...
        Itheta, ...
        'file', 'find_Itheta.m', ...
        'outputs', {'Ihteta'}, ...
        'Optimize', false ...
    });
submit(job)
job.Tasks


wait(job)


