function INT_C2 = find_INT_C2(C21,C22,C23)
%find_INT_C2
%    INT_C2 = find_INT_C2(C21,C22,C23)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2022 19:08:24

INT_C2 = [0.0;0.0;0.0;-C21;-C22;-C23;-C21;-C22;-C23;-C21;-C22;-C23;0.0;0.0;0.0;0.0;0.0;0.0];
