function INT_C0 = find_INT_C0(C01,C02,C03)
%find_INT_C0
%    INT_C0 = find_INT_C0(C01,C02,C03)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2022 19:08:10

INT_C0 = [0.0;0.0;0.0;-C01;-C02;-C03;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
