function INT_Bg0 = find_INT_Bg0(Bg01,Bg02,Bg03,Lg01,Lg02,Lg03,m0u)
%find_INT_Bg0
%    INT_Bg0 = find_INT_Bg0(Bg01,Bg02,Bg03,Lg01,Lg02,Lg03,M0U)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2022 19:08:08

INT_Bg0 = [-Bg01.*m0u;-Bg02.*m0u;-Bg03.*m0u;Bg02.*Lg03.*m0u-Bg03.*Lg02.*m0u;-Bg01.*Lg03.*m0u+Bg03.*Lg01.*m0u;Bg01.*Lg02.*m0u-Bg02.*Lg01.*m0u;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
