function INT_C3 = find_INT_C3(C31,C32,C33)
%find_INT_C3
%    INT_C3 = find_INT_C3(C31,C32,C33)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2022 19:08:24

INT_C3 = [0.0;0.0;0.0;-C31;-C32;-C33;-C31;-C32;-C33;-C31;-C32;-C33;-C31;-C32;-C33;0.0;0.0;0.0];
