function INT_Bg1 = find_INT_Bg1(Bg11,Bg12,Bg13,L01,L02,L03,Lg11,Lg12,Lg13,m1)
%find_INT_Bg1
%    INT_Bg1 = find_INT_Bg1(Bg11,Bg12,Bg13,L01,L02,L03,Lg11,Lg12,Lg13,M1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2022 19:08:08

INT_Bg1 = [-Bg11.*m1;-Bg12.*m1;-Bg13.*m1;-Bg13.*(L02.*m1+Lg12.*m1)+Bg12.*(L03.*m1+Lg13.*m1);Bg13.*(L01.*m1+Lg11.*m1)-Bg11.*(L03.*m1+Lg13.*m1);-Bg12.*(L01.*m1+Lg11.*m1)+Bg11.*(L02.*m1+Lg12.*m1);Bg12.*Lg13.*m1-Bg13.*Lg12.*m1;-Bg11.*Lg13.*m1+Bg13.*Lg11.*m1;Bg11.*Lg12.*m1-Bg12.*Lg11.*m1;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
