function INT_C1 = find_INT_C1(C11,C12,C13)
%find_INT_C1
%    INT_C1 = find_INT_C1(C11,C12,C13)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2022 19:08:10

INT_C1 = [0.0;0.0;0.0;-C11;-C12;-C13;-C11;-C12;-C13;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
