function INT_C4 = find_INT_C4(C41,C42,C43)
%find_INT_C4
%    INT_C4 = find_INT_C4(C41,C42,C43)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2022 19:08:24

INT_C4 = [0.0;0.0;0.0;-C41;-C42;-C43;-C41;-C42;-C43;-C41;-C42;-C43;-C41;-C42;-C43;-C41;-C42;-C43];
